#!/bin/bash

# Define command-line arguments

RESOURCE_TYPE=${1:-node}
NAMESPACE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE $( [ ! -z "$NAMESPACE" ] && echo "-n $NAMESPACE" ) | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  
  if [[ "$RESOURCE_TYPE" ==  "node" ]]
  then
    MEMORY=$(echo $line | awk '{print $4}')
  else
    MEMORY=$(echo $line | awk '{print $3}')
  fi

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo $RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY
done
    
